# Generated by Django 3.2.8 on 2021-10-13 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='destination_id')),
                ('destination_name', models.CharField(max_length=200, unique=True, verbose_name='destination_name')),
                ('aviable', models.BooleanField(default=True, verbose_name='aviable')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Travel',
                'verbose_name_plural': 'Travel',
            },
        ),
        migrations.CreateModel(
            name='PassengerModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='passenger_id')),
                ('birth_date', models.DateField(verbose_name='birth_date')),
                ('document_id', models.CharField(max_length=30, unique=True, verbose_name='document_id')),
                ('document_type', models.CharField(max_length=30, verbose_name='document_type')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unsure')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TravelModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='travel_id')),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(verbose_name='end_date')),
                ('confirmed', models.BooleanField(default=True, verbose_name='confirmed')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travels.destinationmodel', verbose_name='destination_name')),
            ],
            options={
                'verbose_name': 'Travel',
                'verbose_name_plural': 'Travel',
            },
        ),
    ]
