# Generated by Django 3.2.8 on 2021-10-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelmodel',
            name='passenger',
            field=models.ManyToManyField(to='travels.PassengerModel'),
        ),
    ]
