# Generated by Django 3.2.8 on 2021-10-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_travelmodel_passenger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinationmodel',
            options={'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterModelOptions(
            name='passengermodel',
            options={'verbose_name': 'Passenger', 'verbose_name_plural': 'Passengers'},
        ),
        migrations.AlterModelOptions(
            name='travelmodel',
            options={'verbose_name': 'Travel', 'verbose_name_plural': 'Travels'},
        ),
    ]
